[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
normal = { family = "Noto Sans Mono", style = "Regular"}
bold = { family = "Noto Sans Mono", style = "Bold"}
italic = { family = "Noto Sans Mono", style = "Italic"}
bold_italic = { family = "Noto Sans Mono", style = "Bold Italic"}

size = 10.25

[mouse]
hide_when_typing = true

